### ISSUE TITLE
[BUG] optional|required fields are no longer a thing in protobuf 3

### ISSUE THREAD

**Issue by smoya** [asyncapi/protobuf-schema-parser#113]
### Describe the bug.

The following is a protobuf3 valid message

```protobuf
message Example {
    string name = 1;
}
```

As you see, no need for adding `optional` or `required` (e.g. `required string name = 1;`) because such a concept is not present anymore in v3.

However, the parser fails with: ` illegal token 'string' ` unless I add `optional` or `required` keywords.

### Expected behavior

`required` and `optional` keywords are not required (I don't even know if they are legal atm?)

### Screenshots

-

### How to Reproduce

1. I first did this
2. I then did this
3. And so on . . . 

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by GreenRover** [comment]
This is expected behavior. When ever you not give a hint to the protobuf version. V2 will be assumed.

Please try:
```
syntax = "proto3";

message Example {
    string name = 1;
}
```

**Comment by smoya** [comment]
Makes sense. Thanks for the clarification!
