### ISSUE TITLE
Consider upgrading the code to be supported by AsyncAPI Parser-JS v2

### ISSUE THREAD

**Issue by smoya** [asyncapi/protobuf-schema-parser#46]
#### Reason/Context
[Parser-JS 2.0](https://github.com/asyncapi/parser-js/issues/481) (released as rc at this moment) is a completely new parser, with a lot of changes. The bigger ones are:

- Completely rewritten to TS.
- Implements the new [parser-api](https://github.com/asyncapi/parser-api), in particular, the version found in [this PR](https://github.com/asyncapi/parser-api/pull/71/files#diff-ac35ac6e0b0ad3629802a0e04076aa18e94da614f5392e1164dcaacdfe3ee198).
- Uses [Spectral](https://stoplight.io/open-source/spectral) as parser/linter with the [AsyncAPI ruleset](https://meta.stoplight.io/docs/spectral/1e63ffd0220f3-async-api-rules).
- Lots of other improvements, especially around Developer Experience.

Considering that Spectral now validates the documents before parsing, we had to update [the interface](https://github.com/asyncapi/parser-js/tree/next-major#custom-schema-parsers) for Schema parsers to separate validation from parsing. This change also introduced better errors and the way we handle them. (see [this issue](https://github.com/asyncapi/parser-js/issues/480) and related). 

#### Description
- Implement the new Parser-JS 2.0 [Schema Parser Interface](https://github.com/asyncapi/parser-js/tree/next-major#custom-schema-parsers).

Note that Parser-JS v2 uses TypeScript so feel free to use it as well.

**Comment by GreenRover** [comment]
parser-js 2.1.0 is already supported.
PR for integration in react component is open: https://github.com/asyncapi/asyncapi-react/pull/758

Or do i miss something to do?

**Comment by smoya** [comment]
Yeah, I just was moving the issue from https://github.com/GreenRover/proto-schema-parser/issues/2 to here without even checking. Can be closed.

**Comment by smoya** [comment]
@GreenRover I created to crucial issues I consider should be done asap if we want to let people adopt the new protobuf schema format:

- https://github.com/asyncapi/cli/issues/785
- https://github.com/asyncapi/generator/issues/1033
