### ISSUE TITLE
Support ref and import

### ISSUE THREAD

**Issue by bjhartin** [asyncapi/protobuf-schema-parser#61]
#### Reason/Context
I'll just describe my use case:

We have a fairly large set of protobuf definitions which:

- Are hosted in a central location (so ref support is useful)
- Use 'import' to factor out common sub-types to avoid code duplication (so import support is useful)

Our company is large enough that contracts are often multi-party, e.g. some protobufs come from one system but get encoded as base64 and put in a json envelope by another service, etc.  When defining contracts we often want to describe the parts we're responsible for, but provide references to the schemas that aren't ours.

#### Description
- What changes have to be introduced?

I'm not quite sure.

- Will this be a breaking change?

I would not think so because this adds functionality.

- How could it be implemented/designed?

I'm not sure at this time.

**Comment by GreenRover** [comment]
Can you please provide a schema file example?
Where is the schema parser used?
- a code generator?
- the react ui?

**Comment by GreenRover** [comment]
You will find here a pre parser: https://github.com/GreenRover/async-api-validator

This enables you to provide a zip file, containing a spec.yml (or json) and a bunch of proto files.
You have to use $ref in your spec.yaml to point to proto files. The content of the proto files will be integrated into spec.yaml as strings.

**Comment by bjhartin** [comment]
@GreenRover Thanks, and sorry for the late reply.  The preprocessor might work for us.
